version: '3'
services:
  docker-a:
    image: docker-a:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - "../public:/public"
  docker-b:
    image: docker-b:latest
    ports:
      - "3001:3001"
    links:
      - docker-a
    volumes:
      - "../public:/public"
